In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("C:/Users/akkar/data.csv")

In [3]:
df

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [4]:
df.shape

(30, 2)

In [5]:
df.size

60

In [6]:
df.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   YearsExperience  30 non-null     float64
 1   Salary           30 non-null     float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [8]:
df.isnull().sum()

YearsExperience    0
Salary             0
dtype: int64

In [9]:
df.duplicated().sum()

0

In [10]:
df.corr()

YearsExperience    Salary
YearsExperience         1.000000  0.978242
Salary                  0.978242  1.000000

In [11]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
col_list = df.columns # here we are taking all columns other than obj type columns and the dep column

X = df[col_list]
vif_data = pd.DataFrame()
vif_data["feature"] = X.columns
vif_data["VIF"] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]
print(vif_data)

           feature        VIF
0  YearsExperience  37.145972
1           Salary  37.145972


In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X = df['YearsExperience'] 
y = df['Salary'] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0) 

In [20]:
a=np.array(X_train)
a

array([ 9.6,  4. ,  5.3,  7.9,  2.9,  5.1,  3.2,  4.5,  8.2,  6.8,  1.3,
       10.5,  3. ,  2.2,  5.9,  6. ,  3.7,  3.2,  9. ,  2. ,  1.1,  7.1,
        4.9,  4. ])

In [23]:
b=np.array(X_test)
b

array([ 1.5, 10.3,  4.1,  3.9,  9.5,  8.7])

In [17]:
l_model = LinearRegression()

In [21]:
l_model.fit(a.reshape(-1, 1),y_train)

LinearRegression()

In [24]:
predictions = l_model.predict(b.reshape(-1, 1))

In [25]:
predictions

array([ 40748.96184072, 122699.62295594,  64961.65717022,  63099.14214487,
       115249.56285456, 107799.50275317])

In [26]:
from sklearn.metrics import *

In [27]:
r2_on_test = r2_score(y_test,predictions)

In [28]:
r2_on_test

0.988169515729126

In [29]:
X = df['YearsExperience'] 
y = df['Salary'] 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,random_state=0) 

In [30]:
c=np.array(X_train)
c

array([ 3.2,  4.5,  8.2,  6.8,  1.3, 10.5,  3. ,  2.2,  5.9,  6. ,  3.7,
        3.2,  9. ,  2. ,  1.1,  7.1,  4.9,  4. ])

In [31]:
d=np.array(X_test)
d

array([ 1.5, 10.3,  4.1,  3.9,  9.5,  8.7,  9.6,  4. ,  5.3,  7.9,  2.9,
        5.1])

In [33]:
l_model = LinearRegression()

In [34]:
l_model.fit(c.reshape(-1, 1),y_train)

LinearRegression()

In [37]:
predictions = l_model.predict(d.reshape(-1, 1))
predictions

array([ 40950.03066143, 123734.76796394,  65409.15759172,  63527.68628939,
       116208.88275462, 108682.9975453 , 117149.61840578,  64468.42194055,
        76697.98540569, 101157.11233598,  54120.32977774,  74816.51410337])

In [39]:
r2_on_test = r2_score(y_test,predictions)

In [40]:
r2_on_test

0.9679117063698979

#### 1. How many employees having more than 5 years experience are earning more than 60000?

In [ ]:
x= df[df['YearsExperience']>5]
x[x['Salary']>60000].value_counts().sum()

Ans : d 14

#### 2. How many employees are earning between 50000-80000?

In [ ]:
df[(df['Salary']<80000) & (df['Salary']>50000)].value_counts().sum()

Ans: b 12

#### 3. The scatter plot in the following image shows the relationship between the
“YearsExperience” and “Salary” columns. What possible inferences can be drawn from the
plot?

In [ ]:
Answer: A The plot shows a positive correlation between the ‘YearsExperience” and“Salary”column

#### 4. The distribution plot of the column “YearsExperience” is shown in the image below,
what possible inferences can be drawn from the plot.

In [ ]:
b. “YearsExperience” data is positively skewed

#### 5. What all inferences can be drawn from the table shown below

In [ ]:
print(df['YearsExperience'].max() - df['YearsExperience'].min())
print(df['Salary'].max() - df['Salary'].min())

In [ ]:
a. The range of the “YearsExperience” and “Salary” data is (9.4 , 84660 )

#### 6. To split the dataset into training and testing data, if we use the following
code. 
X = data['YearsExperience']
y = data['Salary']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=0) 
What does it mean when we write the test size as 0.2?

In [ ]:
Answer: D. The training data will consist of 80% of the samples from the totalpopulation.

#### 7. In the above example code, we have taken the random state as 0, if we change the
random state as 42, what does it mean for our training and testing data?

In [ ]:
Answer: C The random state does not have any effect on the shape of the data.

#### 8. If the r2 score calculated in the above example is 0.98 , change the sample size of
the training and testing set in the ratio 60:40, and build a linear regression model again.
After plotting the best fit line on the test data, calculate the r2_score for the new model.

In [ ]:
Answer: b. 0.96

#### 9. If while fitting the model with training and testing data, you get the following error
ValueError: Expected 2D array, got 1D array instead: What could be
the issue with the data, and how can you solve it?

In [ ]:
Answer: A Reshape the data to a two dimensional array